<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cab1j_adaptiveimages"
 *
 * Auto generated by Extension Builder 2016-10-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Adaptive Images',
	'description' => 'This extension is generating images in smaller width for responsive websites based on htaccess redirect.',
	'category' => 'fe',
	'author' => 'Marc Bauer',
	'author_email' => 'kontakt@bauer-marc.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);